_version: 1.3

_description: |
  A basic recipes Related component.

_confirmRemoval: true

relatedRecipe:
  _has:
    input: complex-list
    collapse: title
    filter: true
    props:
      -
        prop: title
        _label: Title
        _has:
          input: text
      -
        prop: likes
        _label: Likes
        _has:
          input: text
          type: numbers
      -
        prop: urlImg
        _label: Image
        _has: 
          input: text
      -
        prop: urlRecipe
        _label: Recipe URL
        _has:
          input: text
      -
        prop: normalizedTags
        _label: normalizedTags from tags component
        _has:
          input: text

recipeNormalizedTagsValue:
  _subscribe: normalizedTags
  _has:
    help: This variable is to save the value of the normalizedTags

_groups:
  settings:
    fields:
      - relatedRecipe
    _placeholder:
      height: 80px
      text: Recipes Related
      ifEmpty: relatedRecipe