_description: |
  A basic main recipe component.

_confirmRemoval: true

recipe:
  _placeholder:
    height: 400px
  _component:
    page: true
    include:
      - recipe

recipesRelated:
  _placeholder:
    height: 180px
  _component:
    page: true
    include:
      - recipesRelated
