_description: A layout with special styling for our recipes. Used for

main:
  _placeholder:
    text: Main Section
    height: 600px
  _componentList:
    page: true
    include: 
      - renderers


kilnInternals:
  _componentList:
    internals: true
    include:
      - clay-kiln
