_version: 1.8

_description: |
  A basic recipe component.

_confirmRemoval: true

descriptionRecipe:
  _label: Recipe description
  _publish: pageDescription
  _has:
    input: text

stepInfoRecipe:
  _label: Recipe Steps Information
  _has:
    input: text

preparationTimeStep:
  _label: Preparation Time Step
  _has:
    input: text

readyTimeRecipe:
  _label: Ready Time Recipe
  _has:
    input: text

totalServings:
  _label: Total Servings
  _has:
    input: text

totalCalsPerServings:
  _label: Total Calories
  _has:
    input: text

ingredients:
  _has:
    input: complex-list
    collapse: ingredient
    filter: true
    props:
      - prop: ingredient
        _label: Ingredient
        _has:
          input: text
      - prop: cantMeasure
        _label: Cant Measure
        _has:
          input: text
          type: numbers
      - prop: unitMeasure
        _label: Unit of Measure
        _has:
          input: radio
          options:
            - name: Milligramme (mg)
              value: mg
            - name: Gramme (g)
              value: g
            - name: Kilogramme (kg)
              value: kg
            - name: Millilitre (ml)
              value: ml
            - name: Litre (l)
              value: l
            - name: Pound (lb)
              value: lb
            - name: Ounce (oz)
              value: oz
            - name: Cup (c)
              value: c
            - name: Unit
              value: unit
      - prop: instructions
        _label: Specials Instructions
        _has:
          input: text

nutriFacts:
  _has:
    input: complex-list
    collapse: fact
    filter: true
    props:
      - prop: cantMeasure
        _label: Cant Measure
        _has:
          input: text
          type: numbers
      - prop: unitMeasure
        _label: Unit of Measure
        _has:
          input: radio
          options:
            - name: Milligramme (mg)
              value: mg
            - name: Gramme (g)
              value: g
            - name: Kilogramme (kg)
              value: kg
            - name: Millilitre (ml)
              value: ml
            - name: Litre (l)
              value: l
            - name: Pound (lb)
              value: lb
            - name: Ounce (oz)
              value: oz
            - name: Cup (c)
              value: c
            - name: Unit
              value: unit
      - prop: fact
        _label: Fact Name
        _has:
          input: text

recipeTitle:
  _label: Title of the Recipe
  _publish: pageTitle
  _has:
    input: text

authors:
  _label: Authors of the Recipe
  _publish: pageAuthors
  _has:
    input: simple-list

photosFormatting:
  _label: Quantity of photos
  _has:
    input: text

likesFormatting:
  _label: Quantity of likes
  _has:
    input: text

reviewsFormatting:
  _label: Quantity of reviews
  _has:
    input: text

carousel:
  _component:
    include:
      - carousel

likes:
  _label: Quantity of likes
  _has:
    input: text
    type: numbers

reviews:
  _label: Quantity of Reviews
  _has:
    input: text
    type: numbers

photos:
  _label: Quantity of Photos
  _has:
    input: text
    type: numbers

tags:
  _component:
    include:
      - tags
normalizedTags:
  _subscribe: normalizedTags

carouselUrls:
  _has:
    input: complex-list
  _subscribe: images

recipeDate:
  _has:
    help: This variable is to save the date when the recipe was published.

recipeTime:
  _has:
    help: This variable is to save the time when the recipe was published.

canonicalUrl:
  _has:
    help: This variable is to save the time when the recipe was published.

_groups:
  settings:
    fields:
      - recipeTitle
      - descriptionRecipe
      - authors
      - likes
      - reviews
      - photos
      - stepInfoRecipe (Directions)
      - readyTimeRecipe (Directions)
      - preparationTimeStep (Directions)
      - totalServings (Directions)
      - totalCalsPerServings (Directions)
      - ingredients (Ingredients)
      - nutriFacts (Nutritions Facts)
    _placeholder:
      height: 600px
      text: A Recipe
      ifEmpty: recipeTitle
