_version: 1.6

_description: |
  A basic recipe component.

_confirmRemoval: true

descriptionRecipe:
  _label: Recipe description
  _has:
    input: text

stepInfoRecipe:
  _label: Recipe Steps Information
  _has:
    input: text

preparationTimeStep:
  _label: Preparation Time Step
  _has:
    input: text

readyTimeRecipe:
  _label: Ready Time Recipe
  _has:
    input: text

totalServings:
  _label: Total Servings
  _has:
    input: text

totalCalsPerServings:
  _label: Total Calories
  _has:
    input: text

ingredients:
  _has:
    input: complex-list
    collapse: ingredient
    filter: true
    props:
      -
        prop: ingredient
        _label: Ingredient
        _has:
          input: text
      -
        prop: cantMeasure
        _label: Cant Measure
        _has:
          input: text
          type: numbers
      -
        prop: unitMeasure
        _label: Unit of Measure
        _has: 
          input: radio
          options:
            - 
              name: Milligramme (mg)
              value: mg
            - 
              name: Gramme (g)
              value: g
            - 
              name: Kilogramme (kg)
              value: kg
            - 
              name: Millilitre (ml)
              value: ml
            - 
              name: Litre (l)
              value: l
            - 
              name: Pound (lb)
              value: lb
            - 
              name: Ounce (oz)
              value: oz
            - 
              name: Cup (c)
              value: c
            - 
              name: Unit
              value: unit
      -
        prop: instructions
        _label: Specials Instructions
        _has:
          input: text

nutriFacts:
  _has:
    input: complex-list
    collapse: fact
    filter: true
    props:
      -
        prop: cantMeasure
        _label: Cant Measure
        _has:
          input: text
          type: numbers
      -
        prop: unitMeasure
        _label: Unit of Measure
        _has: 
          input: radio
          options:
            - 
              name: Milligramme (mg)
              value: mg
            - 
              name: Gramme (g)
              value: g
            - 
              name: Kilogramme (kg)
              value: kg
            - 
              name: Millilitre (ml)
              value: ml
            - 
              name: Litre (l)
              value: l
            - 
              name: Pound (lb)
              value: lb
            - 
              name: Ounce (oz)
              value: oz
            - 
              name: Cup (c)
              value: c
            - 
              name: Unit
              value: unit
      -
        prop: fact
        _label: Fact Name
        _has:
          input: text

recipeTitle:
  _label: Title of the Recipe
  _has:
    input: text

author:
  _label: Author of the Recipe
  _has:
    input: text

photosFormatting:
  _label: Quantity of photos
  _has:
    input: text

likesFormatting:
  _label: Quantity of likes
  _has:
    input: text

reviewsFormatting:
  _label: Quantity of reviews
  _has:
    input: text

imgBigUrl:
  _label: Principal Image
  _placeholder:
    height: 255px
    text: Principal image
  _has:
    input: text
    type: url
    help: Image URL

img1:
  _label: Image 1
  _placeholder:
    height: 58px
    text: Image 1
  _has:
    input: text
    type: url
    help: Image URL

img2:
  _label: Image 2
  _placeholder:
    height: 58px
    text: Image 2
  _has:
    input: text
    type: url
    help: Image URL

img3:
  _label: Image 3
  _placeholder:
    height: 58px
    text: Image 3
  _has:
    input: text
    type: url
    help: Image URL

img4:
  _label: Image 4
  _placeholder:
    height: 58px
    text: Image 4
  _has:
    input: text
    type: url
    help: Image URL

likes:
  _label: Quantity of likes
  _has:
    input: text

reviews:
  _label: Quantity of Reviews
  _has:
    input: text

photos:
  _label: Quantity of Photos
  _has:
    input: text

tags:
  _component:
    include:
      - tags
normalizedTags:
  _subscribe: normalizedTags

recipeDate:
  _has:
    help: This variable is to save the date when the recipe was published.

recipeTime:
  _has:
    help: This variable is to save the time when the recipe was published.

canonicalUrl:
  _has:
    help: This variable is to save the time when the recipe was published.

_groups:
  settings:
    fields:
      - recipeTitle
      - descriptionRecipe
      - author
      - likes
      - reviews
      - photos
      - imgBigUrl (Images)
      - img1 (Images)
      - img2 (Images)
      - img3 (Images)
      - img4 (Images)
      - stepInfoRecipe (Directions)
      - readyTimeRecipe (Directions)
      - preparationTimeStep (Directions)
      - totalServings (Directions)
      - totalCalsPerServings (Directions)
      - ingredients (Ingredients)
      - nutriFacts (Nutritions Facts)
    _placeholder:
      height: 600px
      text: A Recipe
      ifEmpty: recipeTitle